baseURL: https://andeeson.com
title: andeeson
paginate: 5
theme: charlolamode

menu:
    main:
        - name: Projects
          url: /projects/
          weight: 30
        - name: Contact
          url: /contact/
          weight: 30

params:
    author: Michael Anderson
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Michael Anderson
        description: |
          Hey, I'm Michael.

          I am a DevSecOps Engineer. 
        
          I like automation, beautiful things, and space.
        imageUrl: "/images/profile.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: My Minecraft Server
              url: https://ardacraft.me

    socialIcons:
        - name: twitter
          url: "https://twitter.com/mikeandeeson"
        - name: instagram
          url: "https://instagram.com/mikeandeeson"
        - name: linkedin
          url: "https://www.linkedin.com/in/mikeandeeson"
        - name: github
          url: "https://github.com/Freshmilkymilk"

    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
